### PR TITLE
Workaround for duplicating recipients (Fix #35)

### LINKED ISSUE #35: Doubled-up addresses
With Thunderbird 68.1.0 and exteditor 2.0.0, I see that after editing a message, some To: or CC:  addresses are "doubled up". To reproduce: start composing a message with more than a single recipient, edit message, see some addresses doubled up. Probably related (but less important) is that after editing, some addresses are near the bottom (not at top) of list of addresses in the compose window.

### PR DESCRIPTION
**Pull request by snipsnipsnip**
It looks like CompFields2Recipients is no longer clearing
existing recipient fields like To, CC, or BCC in Thunderbird 68.
Replicated the original function and modified to workaround.

See also: https://github.com/mozilla/releases-comm-central/commit/b0970cdb9ee7e03bff572da89c4fcc235a6bdd2e
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1525828

### CODE REVIEW

File: chrome/content/exteditor.js [hunk 1]
```diff
@@ -189,7 +189,7 @@ function updateEditor() {
                 if (prefEditHeaders[exteditor_REPLY_TO]) msgCompFields.replyTo = headerHash[exteditor_REPLY_TO.toLowerCase()];
                 if (prefEditHeaders[exteditor_NEWSGROUP]) msgCompFields.newsgroups = headerHash[exteditor_NEWSGROUP.toLowerCase()];
 
-                CompFields2Recipients(msgCompFields);
+                extEditorCompFields2Recipients(msgCompFields);
```
Comment (snipsnipsnip) [inline chrome/content/exteditor.js]: I could keep the call to the broken version of `CompFields2Recipients` and add compatibility stuff around that, but I feared that `CompFields2Recipients` will change behavior again or even be removed since the function seems like dead code to me in the current comm-central.

File: chrome/content/exteditor.js [hunk 2]
```diff
@@ -229,6 +229,60 @@ function updateEditor() {
...
 }
 
+function extEditorCompFields2Recipients(msgCompFields) {
+    // Copied and tweaked from addressingWidgetOverlay.js to keep functionalities as of Thunderbird 60
+
+    let listbox = document.getElementById("addressingWidget");
+    let newListBoxNode = listbox.cloneNode(false);
+    let listBoxColsClone = _menulistFriendlyClone(listbox.itemChildren[0]);
+    newListBoxNode.appendChild(listBoxColsClone);
+    let templateNode = _menulistFriendlyClone(listbox.itemChildren[0]);
```
Comment (snipsnipsnip) [inline chrome/content/exteditor.js]: `_menulistFriendlyClone` is apparently not intended to be used by add-ons,so it may break at some future date.
